const permissions = {
  admin: [
    "/admin/management/chart",
    "/admin/management/table",
    "/admin/search",
    "/admin/management/account",
    "/admin/management/ariticle",
    "/admin/management/data",
    "/admin/management/scoringformulas",
    "/admin/management/point",
    "/home",
    "/role-selection",
    "/profile",
    "/update-profile",
    "/work-process",
    "/notifications",
  ],
  student: [
    "/home",
    "/profile",
    "/update-profile",
    "/work-process",
    "/scientific-paper",
    "/scientific-paper/:id",
    "/add-scientific-paper",
    "/statistics-table",
    "/statistics-chart",
    "/statistics-point",
    "/notifications",
  ],
  lecturer: [
    "/admin/management/chart",
    "/role-selection",
    "/home",
    "/profile",
    "/update-profile",
    "/work-process",
    "/scientific-paper/:id",
    "/admin/management/ariticle",
    "/admin/management/table",
    "/admin/management/point",
    "/scientific-paper",
    "/add-scientific-paper",
    "/statistics-chart",
    "/statistics-table",
    "/statistics-point",
    "/notifications",
  ],
  head_of_department: [
    "/admin/management/chart",
    "/role-selection",
    "/home",
    "/profile",
    "/work-process",
    "/admin/management/account",
    "/admin/management/ariticle",
    "/admin/management/data",
    "/admin/management/table",
    "/admin/management/point",
    "/scientific-paper/:id",
    "/update-profile",
    "/notifications",
  ],
  deputy_head_of_department: [
    "/admin/management/chart",
    "/role-selection",
    "/home",
    "/profile",
    "/work-process",
    "/admin/management/account",
    "/admin/management/ariticle",
    "/admin/management/data",
    "/admin/management/table",
    "/admin/management/point",
    "/scientific-paper/:id",
    "/update-profile",
    "/notifications",
  ],
  department_in_charge: [
    "/admin/management/chart",
    "/role-selection",
    "/home",
    "/profile",
    "/work-process",
    "/admin/management/account",
    "/admin/management/ariticle",
    "/admin/management/data",
    "/admin/management/table",
    "/admin/management/point",
    "/scientific-paper/:id",
    "/update-profile",
    "/notifications",
  ],
};

export default permissions;
